# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20161217_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=50, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='height',
            field=models.FloatField(default=0.0, help_text='CM', verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 1, 21, 47, 10, 464432), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(max_length=50, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.CharField(max_length=80, verbose_name='省'),
        ),
    ]
