# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20170201_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPunish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='奖惩标题')),
                ('content', models.TextField(verbose_name='奖惩内容')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '奖惩',
                'verbose_name_plural': '奖惩',
            },
        ),
        migrations.CreateModel(
            name='RewardPunishLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('level', models.CharField(max_length=50, verbose_name='奖惩等级')),
                ('title', models.CharField(max_length=50, verbose_name='奖惩内容')),
            ],
            options={
                'verbose_name': '奖惩等级',
                'verbose_name_plural': '奖惩等级',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField(default=0.0, verbose_name='总金额')),
                ('pension', models.FloatField(default=0.0, verbose_name='养老保险')),
                ('health', models.FloatField(default=0.0, verbose_name='医疗保险')),
                ('work', models.FloatField(default=0.0, verbose_name='失业保险')),
                ('birth', models.FloatField(default=0.0, verbose_name='生育保险')),
                ('house', models.FloatField(default=0.0, verbose_name='住房公积金')),
                ('tax', models.FloatField(default=0.0, verbose_name='扣税')),
                ('leave', models.FloatField(default=0.0, verbose_name='迟到早退')),
                ('no_work', models.FloatField(default=0.0, verbose_name='旷工')),
                ('due', models.FloatField(default=0.0, verbose_name='实发工资')),
                ('grant', models.BooleanField(default=False, verbose_name='是否发放')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '薪资',
                'verbose_name_plural': '薪资',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='培训主题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='培训内容')),
                ('start', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='结束时间')),
                ('address', models.CharField(max_length=200, verbose_name='培训地点')),
            ],
            options={
                'verbose_name': '培训',
                'verbose_name_plural': '培训',
            },
        ),
        migrations.CreateModel(
            name='TrainEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': '参与培训',
                'verbose_name_plural': '参与培训',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 0, 47, 22, 723547), verbose_name='入职时间'),
        ),
        migrations.AddField(
            model_name='trainemployee',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Employee', verbose_name='参与人'),
        ),
        migrations.AddField(
            model_name='trainemployee',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Train', verbose_name='培训'),
        ),
        migrations.AddField(
            model_name='train',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Employee', verbose_name='培训师'),
        ),
        migrations.AddField(
            model_name='salary',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Employee', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='rewardpunish',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.RewardPunishLevel'),
        ),
        migrations.AddField(
            model_name='rewardpunish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Employee', verbose_name='奖惩人'),
        ),
    ]
