# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-19 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_auto_20170208_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 23, 0, 25, 197867), verbose_name='入职时间'),
        ),
    ]
